### ISSUE TITLE
if not using IO, then turn off in info.yaml and wrapper.v

### ISSUE THREAD

**Issue by mattvenn** [giraypultar/wrapped_keyvalue#2]

**Comment by mattvenn** [comment]
actually it's not a big deal, you don't need to fix this if you don't want

**Comment by giraypultar** [comment]
I'm using buf_io_out, almost like a probe, so I'll leave this in.

https://github.com/giraypultar/wrapped_keyvalue/blob/ba45a3d7de01da0b6ebd001e863bbe7bf02de43a/wrapper.v
